import random
import time

import selenium.common.exceptions
from selenium import webdriver

driver = webdriver.Chrome()









sentences = ["lasers have transformed cardiac surgery",
"she decided to change her name",
"a handful of loose change",
"the death had all the elements of a great tabloid story",
"an assembly plant for imported components",
"the component elements of the armed forces",
"we have encountered one small problem",
"what do we know about the people we encounter in our daily lives?",
"he had learned his lesson by painful experience",
"audition day is an enjoyable experience for any seven-year old",
"a week later I met him in the street",
"icebergs are created when glaciers meet the sea",
"eventually, after midnight, I arrived at the hotel",
"the company has evolved into a major chemical manufacturer",
"the energy evolved during this chemical change is transferred to water",
"motion pictures were to develop into mass entertainment",
"even the best cars emit carbon dioxide",
"It was also a highly desirable political end. Furthermore, it gave the English a door into France",
"moreover, statistics show that competition for places is growing",
"one of his generation's finest songwriters",
"he died from a heart attack at the age of 51",
"an age of technological growth",
"the downturn in the global economy",
"give students a global picture of what is involved in the task",
"worldwide sales of television rights",
"all the stages in the process interact",
"he manipulated the dials of the set",
"the masses were deceived and manipulated by a tiny group",
"the Prime Minister operates a system of divide and rule",
"surgeons operated on on his jaw yesterday morning",
"neutral and non-aligned European nations",
"her tone was neutral, devoid of sentiment",
"the minister cannot be impartial in the way that a judge would be",
"a shy, inoffensive, and sensitive girl",
"the capacity of the freezer is 1.1 cubic feet",
"I was engaged in a voluntary capacity",
"the sewer could not cope with the volume of rainwater",
"the distress call had given the ship's position",
"he moved himself into a reclining position",
"a complex network of water channels",
"a complex of mountain roads",
"a spider constructs a complex network of several different kinds of threads",
"the company has a network of 326 branches",
"the tension and complexities of our contemporary society",
"he was a contemporary of Darwin",
"the pace of modern life",
"Faye peered at her with suspicion",
"the birth rate continued to decline",
"a serious decline in bird numbers",
"subjects as diverse as architecture, language teaching, and the physical sciences",
"their environments are locally various",
"the minority of drivers who persist in drinking",
"his family persevered with his treatment",
"the cost will be in the range of $1–5 million a day",
"the area offers a wide range of activities for the tourist",
"a warehouse with a clear span of 28 feet",
"the stream was spanned by a narrow bridge",
"the room was filled with an assortment of clothes",
"built in 1830, the house retains many of its original features",
"he has been retained as a freelance",
"return one copy to me, keeping the other for your files",
"the guidance system keeps the machine on course",
"the firm employs 150 people",
"the methods they have employed to collect the data",
"a significant increase in sales",
"the gardens are notable for their collection of magnolias and camellias",
"the properties vary in price",
"the second set of data differed from the first",
"the worldwide dominance of Hollywood",
"the supremacy of the king",
"ethnic and cultural rights and traditions",
"the evaluation of each method",
"the assessment of educational needs",
"for no apparent reason she laughed",
"his apparent lack of concern",
"she ate the biscuits with evident enjoyment",
"Ellen's seeming indifference to the woman's fate",
"personal effectiveness in all aspects of life",
"a greenhouse with a southern aspect",
"a well-appointed house with interesting decorative features",
"a special feature on children's reference books",
"he had a practical outlook on life",
"the pleasant outlook from the club window",
"he was questioned on his attitude to South Africa",
"we wanted to marry but circumstances didn't permit",
"the artists are living in reduced circumstances",
"the situation between her and Jake had come to a head",
"the situation of the town is pleasant",
"structuralism is a difficult concept",
"the idea of linking pay to performance has caught on",
"I took a job with the idea of getting some money together",
"the Minister may have exceeded the powers conferred on him by Parliament",
"the officials were conferring with allies",
"I was completely unaware of class distinctions",
"the differences between men and women",
"the couple are patching up their differences",
"some regulation is still required to promote competition",
"she was promoted to General Manager",
"we were encouraged by the success of this venture",
"he advanced towards the dispatch box",
"our knowledge is advancing all the time",
"Mr Gill spotted the manuscript at a local auction and purchased it for £1,500","the horse's hooves fought for purchase on the slippery pavement",
"she bought six first-class stamps",
"wine is rarely a good buy in duty-free shops",
"his knuckles were white as he gripped the steering wheel",
"she was gripped by a feeling of excitement",
"I know I can rely on your discretion",
"differences in earnings depended on a wide variety of factors",
"local authorities complained that they lacked resources",
"sometimes anger is the only resource left in a situation like this",
"quick reflexes were his chief assets",
"either side could break the agreement if it were expedient to do so",
"the current policy is a political expedient",
"students in transition from one programme to another",
"she decided to change her name",
"a handful of loose change",
"an upward trend in sales and profit margins",
"the latest trends in modern dance",
"for students, there is a tendency to socialize in the evenings",
"the work is done in a rather casual fashion",
"the bottles were fashioned from green glass",
"bridges perform the function of providing access across water",
"class shame is a function of social power",
"the purpose of the meeting is to appoint a trustee",
"there was a new sense of purpose in her step as she set off",
"abrupt withdrawal of drug treatment can have serious consequences",
"the past is of no consequence",
"isolation from family and friends may also contribute to anxiety",
"the damage that might arise from the separation of parents and children",
"engineers were working to locate the fault",
"Lindsey looked up to find Neil watching her",
"vitamin B12 is found in dairy products",
"the need to maintain close links between industry and schools",
"the allowance covers the basic costs of maintaining a child",
"he was unable to continue with his job",
"we continue the story from the point reached in Chapter 1",
"the dome was supported by a hundred white columns",
"the government gives £2,500 million a year to support the voluntary sector",
"people consume a good deal of sugar in drinks",
"Carolyn was consumed with guilt",
"he was eating a hot dog",
"these make great party eats",
"buildings can be designed to absorb and retain heat",
"she sat in an armchair, absorbed in a book",
"taxpayers had contributed £141.8 million towards the cost of local services",
"she gave him presents and clothes",
"you gave me such a fright",
"the government's controversial economic policies",
"I have no plans to retire",
"they were planning a trip to Egypt",
"the basic principles of justice",
"he had to accept the truth of her accusation",
"traders have lost £10,000 in revenue since the traffic scheme was implemented","he has a nice home and an adequate income",
"they placed great emphasis on the individual's freedom",
"inflection and emphasis can change the meaning of what is said",
"she came to prominence as an artist in the 1960s",
"the distribution of stress is uniform across the bar",
"he's obviously under a lot of stress",
"the protection of fundamental human rights",
"two courses cover the fundamentals of microbiology",
"certain basic rules must be obeyed",
"I learnt the basics of programming on a course",
"I learnt the basics of programming on a course",
"the two sisters were to accompany us to London",
"the illness is often accompanied by nausea",
"the plight of the refugees was acknowledged by the authorities",
"she refused to acknowledge my presence",
"the Home Office finally admitted that several prisoners had been injured",
"old-age pensioners are admitted free to the museum",
"some of the customers greeted the barman in Gaelic",
"she feels that he does not appreciate her",
"they failed to appreciate the pressure he was under",
"your support is of great value",
"they internalize their parents' rules and values",
"the plight of the refugees was acknowledged by the authorities",
"she refused to acknowledge my presence",
"the processor comes complete with a blender attachment",
"she felt a sentimental attachment to the place creep over her",
"optional accessories include a battery charger and shoulder strap",
"she was charged as an accessory to murder",
"there was a bond of understanding between them",
"press the material to bond the layers together",
"there was a bond of understanding between them",
"press the material to bond the layers together",
"the tap was joined to a pipe",
"it was soldered so well that you couldn't see the join",
"years of wrangling over a controversial bypass",
"information leaflets are being distributed to hotels",
"the birds are mainly distributed in marshes and river valleys",
"storms can disperse seeds via high altitudes",
"a property suitable for occupation by older people",
"the youth hostel has been adapted from a private residence",
"the helmet has been reinforced with a double layer of cork",
"he advises an application of fluoride to strengthen the teeth",
"foundations were being dug for a block of flats",
"this idea is the foundation of all modern economics",
"he suddenly lost his footing",
"attempts to establish the shop on a firm financial footing",
"the guide is illustrated with full-colour photographs",
"the World Cup illustrated what high standards our players must achieve",
"the town was decorated with Christmas lights",
"he was decorated for outstanding bravery",
"the best dry sherry is exemplified by the fino of Jerez",
"he exemplified his point with an anecdote",
"his mind soared to previously unattainable heights of insight",
"we shall allow our intuition to guide us",
"his preferred mode of travel was a kayak",
"in the Seventies the mode for active wear took hold",
"taking notes in an unobtrusive manner",
"his arrogance and pompous manner",
"the work is done in a rather casual fashion",
"the bottles were fashioned from green glass",
"she may be prepared to modify her views",
"Eliot was persuaded to alter the passage",
"adequate insurance cover is difficult to obtain",
"the price of silver fell to that obtaining elsewhere in the ancient world",
"I got a letter from him the other day",
"Nigel got home very late",
"it is hard for logic to prevail over emotion",
"she was prevailed upon to give an account of her work",
"I managed to acquire all the books I needed",
"adequate insurance cover is difficult to obtain",
"the price of silver fell to that obtaining elsewhere in the ancient world",
"I've made a few adjustments to my diet",
"the adaptation of teaching strategy to meet students' needs",
"topics which assume detailed knowledge of local events",
"he assumed full responsibility for all organizational work",
"I presumed that the man had been escorted from the building",
"kindly don't presume to issue me orders in my own house",
"he accepted a pen as a present",
"this tentative explanation came to be accepted by the men",
"the various categories of research",
"it has good accommodation for a hotel of this class",
"people who are socially disenfranchised by class",
"the world is constantly changing",
"the sun always rises in the east",
"if the marriage doesn't work out, we can always get divorced",
"the waste is disposed of in the North Sea",
"prolactin, a calming hormone, is released, disposing you towards sleep",
"staff are to be active participants in the decision-making process",
"his mouth fell open as he perceived the truth",
"if Guy does not perceive himself as disabled, nobody else should",
"most guidebook history is written from the editor's perspective",
"he had a practical outlook on life",
"the pleasant outlook from the club window",
"he has a prior engagement this evening",
"we ate an early lunch",
"an early goal secured victory",
"the Union decided last night to recommend rejection of the offer",
"he became tired of his friend's refusal to see him",
"there are fears for the political stability of the area",
"burglars fled empty-handed after triggering the alarm",
"fumes from cooking are enough to activate the alarm",
"the organization had lost its vision and direction",
"the idea came to him in a vision",
"she'd never been blessed with a vivid imagination",
"black ravens emerged from the fog",
"United have emerged as the bookies' clear favourite",
"at low tide the sands are exposed",
"he has been exposed as a liar and a traitor",
"Brenda was forced to reveal Robbie's whereabouts",
"he uncovered the face of the dead man",
"further evidence has been uncovered",
"a serious instance of corruption",
"I instanced Bob as someone whose commitment had certainly got things done",
"advertising provides a good example of an industry where dreams have faded",
"it is important that parents should set an example",
"authors who are highly regarded by their peers tend to be cited",
"he has been cited many times for his contributions in the intelligence area",
"the pain grew in intensity",
"hydrothermal processes of low intensity",
"cycling can help you build up your strength",
"they were taking no chances with the strength of the retaining wall",
"cycling can help you build up your strength",
"they were taking no chances with the strength of the retaining wall",
"he was primarily motivated by the desire for profit",
"the violence prompted a wave of refugees to flee the country",
"‘And the picture?’ he prompted",
"we have confidence in the accuracy of the statistics",
"Eliot was persuaded to alter the passage",
"she decided to change her name",
"a handful of loose change",
"a challenge to the legality of the banning order",
"it is possible to challenge the report's assumptions",
"we hope this leaflet has been helpful in answering your questions",
"four men were being questioned about the killings",
"the injuries are consistent with falling from a great height",
"computerized design methods will be demonstrated",
"their shameful silence demonstrates their ineptitude",
"Brenda was forced to reveal Robbie's whereabouts",
"both firms deny any responsibility for the tragedy",
"the inquiry was denied access to intelligence sources",
"the survey appears to contradict the industry's claims",
"they derived great comfort from this assurance",
"adequate insurance cover is difficult to obtain",
"the price of silver fell to that obtaining elsewhere in the ancient world",
"the final dimensions of the pond were 14 ft x 8 ft",
"we must focus on the cultural dimensions of the problem",
"the proportion of greenhouse gases in the atmosphere is rising",
"personal effectiveness in all aspects of life",
"a greenhouse with a southern aspect",
"the final phases of the war",
"there is no need at this stage to give explicit details",
"there are only two characters on stage",
"some roads may have to be closed at peak times to restrict the number of visitors",
"try to limit the amount you drink",
"they came here to seek shelter from biting winter winds",
"an improvement in the status of women",
"their standing in the community",
"an inter-departmental squabble of long standing",
"police are trying to trace a white van seen in the area",
"trace a map of the world on to a large piece of paper",
"the problem is telling which is the original document and which the copy",
"the record has sold more than a million copies",
"there was widespread support for the war",
"the arrangements were outlined in very general terms",
"a policy that would eliminate inflation",
"Customs officials removed documents from the premises",
"exchange controls have finally been removed",
"he had a hand in my exclusion from the committee",
"barring accidents, we should win",
"schools were located in the same campus to facilitate the sharing of resources",
"players gained improved flexibility in their ankles",
"an excellent combination of strength, pliability, and elasticity",
"the school takes a maximum of 32 pupils",
"in past years we didn't allocate enough funds to infrastructure maintenance",
"equal time was allotted to each",
"the train approached the main line",
"the department had been approached about funding",
"Congress had assigned the task to the agency",
"managers happily assign large sums of money to travel budgets",
"in past years we didn't allocate enough funds to infrastructure maintenance",
"the cash had been earmarked for a big expansion of the programme",
"this car has all the earmarks of a classic",
"she was frowning in concentration",
"the island has the greatest concentration of seabirds in the north-west",
"a position of considerable influence",
"a sizeable proportion of the population",
"last night's debate on the Education Bill",
"MPs debated the issue in the Commons",
"I discussed the matter with my wife",
"a campaign to woo potential customers",
"a young broadcaster with great potential",
"surely it's not possible for a man to live so long?",
"the possible effects of global warming",
"relegation remains a distinct possibility",
"it was not yet ten o'clock, so presumably the boys were still at the pub",
"matters have improved somewhat since then",
"an exhibition of French sculpture",
"the visit was an indication of the improvement in relations between the countries",
"flowers are often given as a sign of affection",
"she gave him the thumbs-up sign",
"innovation is crucial to the continuing success of any organization",
"she decided to change her name",
"a handful of loose change",
"the staircase gives access to the top floor",
"I was suddenly overcome with an access of rage",
"the southern entrance of the palace",
"at their abrupt entrance he rose to his feet",
"the house was not fit for human habitation",
"my family keep fit by walking and cycling",
"he had absolute authority over his subordinates",
"health authorities issued a worldwide alert",
"the power of the storm",
"they conclude their study with these words",
"the doctors concluded that Esther had suffered a stroke",
"they were straining to finish the job",
"the interior was finished with American oak",
"a conventional morality had dictated behaviour",
"it's quite normal for puppies to bolt their food",
"negotiations were at a crucial stage",
"Japan's pivotal role in the world economy",
"the receptors are developed and differentiated into sense organs",
"lasers have transformed cardiac surgery",
"the palace used to display a series of tapestries",
"he could exhibit a saintlike submissiveness",
"a challenge which has no parallel in peacetime this century",
"the increase in the quality of wines has paralleled the rise of interest in food",
"the minister held talks with his French counterpart",
"some people resemble their dogs",
"they had sufficient resources to survive",
"there's too much work and not enough people to do it",
"knowledge is transmitted from teacher to pupil",
"the programme was transmitted on 7 October",
"the announcement was broadcast live",
"the second method is to broadcast the seeds together with not more than 1 kg to the acre of rapeseed",
"he underwent a life-saving brain operation",
"a call for volunteers to act as foster-parents",
"volunteering is an easy way to get involved in practical conservation",
"the scheme was established in 1975",
"the police established that the two passports were forgeries",
"the concept is difficult to prove",
"many vehicle journeys (and hence a lot of pollution) would be saved",
"a road accident left him severely injured",
"high interest rates are hurting the local economy",
"rolling properly into a fall minimizes hurt",
"the build-up of military activity",
"as a young man he joined the military and pursued a career in the Army",
"hospitals have had to be adapted for modern medical practice",
"she may be prepared to modify her views",
"a journey of approximately two hours",
"the man picked me up roughly",
"this is a walk of roughly 13 miles",
"the committee must assess the relative importance of the issues",
"the study will assist in evaluating the impact of recent changes",
"the proportion of greenhouse gases in the atmosphere is rising",
"divide the circle into three equal parts",
"she played a lot of leading parts",
"a hormone which regulates metabolism",
"the whole operation is under the control of a production manager",
"platelet activity was higher in patients with the disease than in the controls",
"the situation was unique in British politics",
"juniper berries give gin its distinctive flavour",
"the health ministry has sole federal responsibility for healthcare",
"we offer a 10-year guarantee against rusting",
"no one can guarantee a profit on stocks and shares",
"the car comes with a three-year warranty",
"what happened to all those firm promises of support?",
"he showed great promise even as a junior officer",
"he views that season as the highlight of his career",
"the issues highlighted by the report",
"salesmen who use jargon to imply superior knowledge",
"comments seen as implicit criticism of the policies",
"an implicit faith in God",
"any form of mountaineering has its inherent dangers",
"access to the arts is intrinsic to a high quality of life",
"the person appointed has fully justified our confidence",
"the alcohol content is clearly stated on the label",
"the label ‘salsa’ seems especially meaningless when applied to musicians like Tito Puente",
"he gave his pet a collar with a metal name tag",
"mothers suspected that their babies had been wrongly tagged during an alarm at the hospital",
"a leader's designation of his own successor",
"arrange a layer of aubergines in a dish",
"he saw the pilot slumped in his cockpit and went to his aid",
"women were aided in childbirth by midwives",
"they helped her with domestic chores",
"I asked for help from my neighbours",
"a country under arbitrary government",
"the country comprises twenty states",
"he remains a great leader despite age and infirmity",
"the accident occurred at about 3.30 p.m.",
"two hours had passed and still nothing had happened",
"it is the outcome of the vote that counts",
"the tower collapsed as a result of safety violations",
"the results are evaluated by the researcher",
"he was advised to terminate the contract",
"their ultimate aim was to force his resignation",
"the ultimate in decorative luxury",
"it's impossible to predict the eventual outcome of the competition",
"a matter of the utmost importance",
"a plot that stretches credulity to the utmost",
"the sewer could not cope with the volume of rainwater",
"the capacity of the freezer is 1.1 cubic feet",
"I was engaged in a voluntary capacity",
"bicycle hire for the duration of your holiday",
"the rapid expansion of suburban London",
"the upward growth of plants",
"test results can be inputted by the technician in the laboratory",
"the aim is to minimize costs",
"statements which, although literally true, are nevertheless misleading",
"her natural mother had abandoned her at an early age",
"he had clearly abandoned all pretence of trying to succeed",
"we feel our public representatives have deserted us",
"Isabella offered to renounce her son's claim to the French Crown",
"authors who are highly regarded by their peers tend to be cited",
"he has been cited many times for his contributions in the intelligence area",
"I realized she was quoting passages from Shakespeare",
"a garage quoted him £30",
"he was commended by the judge for his courageous actions",
"I commend her to you without reservation",
"I wanted to devote more time to my family",
"in past years we didn't allocate enough funds to infrastructure maintenance",
"the new law is expected to diminish the government's chances",
"operations in the southern sector of the North Sea",
"check to ensure that all nuts and bolts are secure",
"his position as party leader was less than secure",
"she twisted her handkerchief into a tight knot",
"he won in a tight finish",
"it's certain that more changes are in the offing",
"he raised certain personal problems with me",
"this thought had sustained him throughout the years",
"he sustained severe head injuries",
"a few words of comfort",
"he underwent a life-saving brain operation",
"vitamin C helps your body utilize the iron present in your diet",
"the evidence would enable us to arrive at firm conclusions",
"the troops were authorized to use force",
"the client must ensure that accurate records are kept",
"it was the barest of welcomes, but it was a welcome nonetheless",
"this office is perfectly adequate for my needs",
"they had sufficient resources to survive",
"she anticipated scorn on her return to the theatre",
"he anticipated Bates's theories on mimicry and protective coloration",
"it's as well to expect the worst",
"other new measures are foreshadowed in the White Paper",
"clarify your objectives and ways of attaining them",
"he achieved his ambition to become a press photographer",
"most people are aware of the dangers of sunbathing",
"I'm quite capable of taking care of myself",
"she looked enthusiastic and capable",
"commodities such as copper and coffee",
"the items on the agenda",
"I realized she was quoting passages from Shakespeare",
"a garage quoted him £30",
"he recited passages of Dante",
"the coup leader promised an election but did not specify a date",
"the state of the company's finances",
"Germany, Italy, and other European states",
"one might question the validity of our data",
"the French domains of the Plantagenets",
"the defence of the realm",
"the arrangement had not been made explicit",
"the clear glass of the French windows",
"with a clear road ahead he shifted into high gear",
"a conservatory in a delicate framework of iron",
"he had had the photo framed",
"staff have proved invaluable in framing the proposals",
"the implication is that no one person at the bank is responsible",
"our implication in the problems",
"here are some suggestions for tackling the problem",
"there is no suggestion that he was involved in any wrongdoing",
"a debate over private investment in road-building",
"the company is to invest £12 m in its manufacturing site at Linlithglow",
"the passage of time has invested the words with an unintended humour",
"a pub has to be licensed by the local justices",
"she was now a mature woman",
"children mature at different ages",
"children should be accompanied by an adult",
"children have different notions about the roles of their parents",
"she had a notion to ring her friend at work",
"the idea of linking pay to performance has caught on",
"I took a job with the idea of getting some money together",
"I had an almost irresistible impulse to giggle",
"an added impulse to this process of renewal",
"a crowd had assembled outside the gates",
"my new machine is being assembled and my old one dismantled",
"Tony assured me that there was a supermarket in the village",
"we guarantee to assure your life",
"he understood her feelings and tried to reassure her",
"the roof collapsed on top of me",
"he collapsed from loss of blood",
"the faint murmur of voices",
"the heat made him feel faint",
"time constraints make it impossible to do everything",
"planning restrictions on commercial development",
"the plan has the interests of children at its core",
"the station has a central courtyard",
"his preoccupation with history is central to his work",
"output from the mine ceased in May",
"banning the production of chemical weapons",
"members are entitled to a discount on production of their membership card",
"a portion of the jetty still stands",
"what will be my portion?",
"divide the circle into three equal parts",
"she played a lot of leading parts",
"financial support was not forthcoming",
"refreshments will be available all afternoon",
"the eastern margin of the Indian Ocean",
"they won by a convincing 17-point margin",
"a willow tree at the water's edge",
"his cars have the edge over his rivals'",
"he peeped through the gap in the curtains",
"there are many gaps in our understanding of what happened",
"he is training for the ministry",
"Gladstone's first ministry was outstanding",
"there was evidence of bias against foreign applicants",
"a turquoise silk dress cut on the bias",
"prejudice against people from different backgrounds",
"prejudice resulting from delay in the institution of the proceedings",
"residents jump up and down on their rubbish to reduce its bulk",
"the bulk of the traffic had passed",
"the schools varied in size",
"in the majority of cases all will go smoothly",
"kids get control of the money when they reach the age of majority",
"publication is timed to coincide with a major exhibition",
"the interests of employers and employees do not always coincide",
"that takes his tally to 10 goals in 10 games",
"their signatures should tally with their names on the register",
"he ignored contrary advice and agreed on the deal",
"she is sulky and contrary where her work is concerned",
"a crowd gathered on the opposite side of the street",
"a word that is opposite in meaning to another",
"Kate's perverse decision not to cooperate held good",
"in two general elections the outcome was quite perverse",
"the officer pursued the van",
"Brenda was forced to reveal Robbie's whereabouts",
"I do not want to divulge my plans at the moment",
"in a straightforward case no fees will be charged",
"he was an extraordinarily uncomplicated man",
"soya milk is used as a substitute for dairy milk",
"dried rosemary can be substituted for the fresh herb",
"negotiations should lead to an exchange of land for peace",
"there was a heated exchange",
"these results can be summarized in the following table",
"against all odds the child survived",
"a firm of builders undertook the construction work",
"police have launched an initiative to tackle rising crime",
"the first scoring chance came when Orrell tackled Webb",
"they provided considerable empirical evidence to support their argument",
"she observed that all the chairs were already occupied",
"a tribunal must observe the principles of natural justice",
"the organization has issued guidelines for people working with prisoners",
"the committee put forward forty recommendations for change",
"four girls in identical green outfits",
"a soft cheese similar to Brie",
"from these facts we can infer that crime has been increasing",
"little can be safely deduced from these figures",
"while abroad he had kept a journal",
"the local authority must compile a list of the names and addresses of taxpayers",
"a crowd had assembled outside the gates",
"my new machine is being assembled and my old one dismantled",
"a design consultancy whose principal is based in San Francisco",
"the winners are paid from the interest without even touching the principal",
"I asked my boss for a promotion",
"he does not like being bossed around",
"the consortium could proceed with the plan",
"from the High Street, proceed over Magdalen Bridge",
"Peter had just begun a life sentence for murder",
"he went out to the shops",
"the food is going bad",
"a radical overhaul of the existing regulatory framework",
"the country has had a socialist revolution",
"the authorities put down a rebellion by landless colonials",
"the theory was developed subsequent to the earthquake of 1906",
"he attracted a worldwide following",
"the following day there was a ceremony in St Peter's Square",
"the theme of the sermon was reverence",
"the aircraft were in violation of UN resolutions",
"the publishing of misleading advertisements was a contravention of the Act",
"they were granted a meeting",
"he hasn't made much progress, I'll grant you that",
"the dissident was allowed to leave the country",
"he allowed that the penalty appeared too harsh for the crime",
"the Home Office finally admitted that several prisoners had been injured",
"old-age pensioners are admitted free to the museum",
"the pickets induced many workers to stay away",
"none of these measures induced a change of policy",
"it wasn't easy, but I persuaded him to do the right thing",
"the evidence is difficult to interpret",
"I agreed to interpret for Jean-Claude",
"they explained that their lives centred on the religious rituals",
"several of his books were translated into English",
"she had been translated from familiar surroundings to a foreign court",
"after his departure, there was an interval of many years without any meetings","in the interim I'll just keep my fingers crossed",
"historians try to be objective and impartial",
"the system has achieved its objective",
"the minister cannot be impartial in the way that a judge would be",
"aim the camcorder at some suitable object",
"the programme will aim at deepening understanding",
"the hostilities ceased and normal life was resumed",
"they were comparatively civil to their daughter",
"they thought she was wrong but were too polite to say so",
"the hire charge is computed on a daily basis",
"the program can calculate the number of words that will fit in the space available",
"his last words were calculated to wound her",
"lone parents constitute a great proportion of the poor",
"the superior courts were constituted by the Judicature Acts 1873–5",
"he inaugurated a new policy of trade and exploration",
"the parameters within which the media work",
"a conservatory in a delicate framework of iron",
"the women were portrayed as passive victims",
"a submissive, almost sheeplike people",
"the bombardment was resumed as a preliminary to an infantry attack",
"a ceasefire had been agreed as a prelude to full peace negotiations",
"signatories to the Montreal Protocol",
"the two officers nodded in agreement",
"one unit is equivalent to one glass of wine",
"the French equivalent of the Bank of England",
"add equal amounts of water and flour",
"the players proved equal to the task",
"the minister held talks with his French counterpart",
"the contract, when signed, is filed",
"silk is categorized as a luxury import",
"the forlorn hope of finding a peace formula",
"polite formulas and stock phrases",
"sea salt is usually available in coarse or fine grades",
"I got good grades last semester",
"the various categories of research",
"the blow left a red mark down one side of her face",
"the first syllable has a stress mark",
"exam results may serve as an index of the teacher's effectiveness",
"he guided her to the front row and sat beside her",
"his life was guided by his religious beliefs",
"the rule was amended to apply only to non-members",
"the book was published in 1960 and revised in 1968",
"students frantically revising for exams",
"no change may be made without the consent of all the partners",
"he consented to a search by a detective",
"the two officers nodded in agreement",
"they improved standards in consultation with consumer representatives",
"the carved heads described in the poem correspond to a drawing of Edgcote House",
"Margaret corresponded with him until his death",
"a team from the power company came to shift the cables away from the house",
"a shift in public opinion",
"she moved to the door",
"aircraft design had moved forward a long way",
"a slight movement of the body",
"the movement towards greater sexual equality",
"a revised version of the paper was produced for a later meeting",
"he told her his version of events",
"if only we knew the sort of people she was mixing with",
"the problem with the engine was soon sorted",
"the minister reported a decline in milk production",
"Stewart is to report to a probation office on Monday",
"an increased incidence of cancer",
"vandalism used to be a rare occurrence",
"a gentleman of complete integrity",
"upholding territorial integrity and national sovereignty",
"they spoke with convincing honesty about their fears",
"the aircraft suffered minimal damage",
"he was a school monitor and a choir boy",
"equipment was installed to monitor air quality",
"she observed that all the chairs were already occupied",
"a tribunal must observe the principles of natural justice",
"investigators have yet to accumulate enough evidence",
"as soon as a crowd gathered, the police came",
"information that we have gathered about people",
"the president made a brief working visit to Moscow",
"a pair of extremely brief black shorts",
"visiting London for a short break",
"my knowledge of music is extremely skimpy",
"an assembly plant for imported components",
"the component elements of the armed forces",
"divide the circle into three equal parts",
"she played a lot of leading parts",
"the constituent minerals of the rock",
"the MP is playing on his constituents' sense of regional identity to win votes",
"the sheer number of visitors is posing a threat to the area",
"the prime minister posed for photographers",
"lone parents constitute a great proportion of the poor",
"the superior courts were constituted by the Judicature Acts 1873–5",
"a nurse's prime concern is the well-being of the patient",
"you're in the prime of life",
"the paper has lost millions of readers since its heyday in 1964",
"I'm sure there's a perfectly rational explanation",
"signs of recovery in the housing market",
"a team of salvage experts to ensure the recovery of family possessions",
"she kept her resolution not to see Anne any more",
"he handled the last British actions of the war with resolution",
"she was full of good intentions",
"those who succeed because of sheer grit and determination",
"order was eventually restored by riot police",
"the union threatened strike action if Owen was not reinstated",
"the occupational sick pay scheme",
"I have no plans to retire",
"they were planning a trip to Egypt",
"we widened the scope of our investigation",
"the scope for major change is always limited by political realities",
"an enclosure ten acres in extent",
"everyone will have to compromise to some extent",
"the light was suspended from the ceiling",
"that's where people are supposed to hang their washing",
"he was hanged for murder",
"they don't give a damn about the welfare of their families",
"an improvement in the patient's well-being",
"the role of the police is to enforce the law",
"the decision was theirs and was not imposed on them by others",
"she realized that she had imposed on Mark's kindness",
"he acted in ignorance of basic procedures",
"give farmers an incentive to improve their land",
"companies were prepared to build only in return for massive inducements",
"initially, he thought the new concept was nonsense",
"a third motor powers the tape eject mechanism",
"the immune system's mechanism for detecting pathogens",
"the police are now reviewing procedures",
"the cottages accommodate up to six people",
"any language must accommodate new concepts",
"he has 28 days in which to lodge an appeal",
"they had to remove a bullet lodged near his spine",
"they helped her with domestic chores",
"I asked for help from my neighbours",
"an automatic kettle that switches itself off when it boils",
"automatic physical functions such as breathing",
"payments were made to farmers to compensate them for cuts in subsidies",
"the manager is hoping for victory to compensate for the team's dismal league campaign",
"offenders should recompense their victims",
"adequate recompense for workers who lose their jobs",
"he believes that books may be displaced by the electronic word",
"he drained his glass and replaced it on the bar",
"museums and art galleries which had previously been open to the public",
"the lorry reversed into the back of a bus",
"the damage done to the ozone layer may be reversed",
"at the back of the hotel is a secluded garden",
"he moved back a pace",
"Eliot was persuaded to alter the passage",
"the book was published in 1960 and revised in 1968",
"students frantically revising for exams",
"the rule was amended to apply only to non-members",
"the scenarios for four short stories",
"the two men are serving sentences for plotting a bomb campaign",
"he started to plot lines of ancient sites",
"the content of the programme should follow a logical sequence",
"she had been secretary to a succession of board directors",
"the new king was already elderly at the time of his succession",
"red ochre intended to simulate blood",
"his style was imitated by many other writers",
"the original settlers were forced to submit to Bulgarian rule",
"the panel's report was submitted to a parliamentary committee",
"they were looking for their fifth successive win",
"five consecutive months of serious decline",
"the state instituted a national lottery",
"his sons were instituted to the priesthood",
"we're planning to install a new shower",
"he was installed as Prime Minister in 1966",
"an eminent man of great intelligence",
"the chief of military intelligence",
"he is under investigation for receiving illicit funds",
"an examination of marketing behaviour",
"he scraped through the examinations at the end of his first year",
"glaciers are interesting natural phenomena",
"the band was a pop phenomenon just for their sales figures alone",
"vandalism used to be a rare occurrence",
"she marvelled at Jeffrey's composure",
"the ratio of men's jobs to women's is 8 to 1",
"the proportion of greenhouse gases in the atmosphere is rising",
"a campaign by the prisoner's mother resulted in his release",
"they were freed from jail",
"his inheritance freed him from financial constraints",
"the initiative was with those lower down in the hierarchy",
"his ‘steady state’ hypothesis of the origin of the universe",
"he acted outside his authority when he intervened in the dispute",
"I prayed that she would intercede for us",
"the programmes of study will apply from five years of age, likewise the attainment targets",
"I stuck out my tongue and Frankie did likewise",
"a brilliant linguist, he was also interested in botany",
"his design team commenced work",
"Peter had just begun a life sentence for murder",
"the dam project was originally conceived in 1977",
"we had no definite plans",
"the arrangement had not been made explicit",]



for sentence in sentences:
    driver.get(f"https://translate.google.com/?hl=tr&sl=en&tl=tr&text={sentence}&op=translate")

    for i in range(20) :
        try:
            time.sleep(0.2)
            translate = driver.find_element_by_xpath(
                '//*[@id="yDmH0d"]/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[3]/c-wiz[2]/div[6]/div/div[1]/span[1]/span/span').text
            print('"'+sentence+'":"'+translate+'",')
            break
        except :
            1+0





